### PR TITLE
make some classes and fields accessible for being extended

### PR DESCRIPTION
**Pull request by yichen88**

### CODE REVIEW

**Comment by lucastheisen** [comment]
I don't really have a problem adding this, but I do think its probably a bad idea.  If you are _setting_ the `CommandRunner`, you are not allowing the JVM to do its normal SPI configuration of the filesystem.  Can you describe your specific use case?  Why would you want to do this?  Because this is an SPI registered package, the filesystem itself is shared.  So if you set the `CommandRunner` it would affect other things that already had a reference to the current FileSystem...  Are you sure you want to do this?

**Comment by yichen88** [comment]
i would like to add a lock on channels to limit connections in multi-thread. So i have to set a MyCommandRunner that initialize MyChannel for create/delete operations by Files.
Thanks.

**Comment by lucastheisen** [comment]
Fair enough...  Just released as version 1.0.6.  Should show up on central soon.  Thanks!

**Comment by lucastheisen** [comment]
Crap, i missed that... gonna need to re-release this after that (to keep dep version inline)...  Should be done soon.

**Comment by lucastheisen** [comment]
Re-released as 1.0.7 to include the updated version of jsch-extension with your pull request.  Should be available soon on central...

**Pull request merged**
