### PR TITLE
Create directory using sftp commands

### PR DESCRIPTION
**Pull request by bpiwowar**
This allows to perform more checks to deliver the proper answer (i.e. FileAlreadyExistsException if the directory already exists)

### CODE REVIEW

**Comment by lucastheisen** [comment]
I decided not to merge this fix for a couple reasons.  First, `sftp` is capable of 95% of a `FileSystem`, so my end goal is to have a full `SftpFileSystem` implementation alongside the `UnixSshFileSystem`.  Second, this approach confuses the abstraction.  That said, this is a good idea.  So as a transitional approach, I created a second filesystem with uri scheme `sshSftpHybrid.unix`.  This is an extension of the current `ssh.unix` filesystem with an overridden `createDirectory` per your implementation.  So it is effectively the same outcome as your pull request but it keeps the abstractions distinct.  If you feel like adding more `sftp` overrides, you have a good place for that now.  Also, that work will serve as a prototype for a full `sftp` implementation.  I also added a unit test to verify the `createDirectory` over sftp.  Please give this a try and let me know what you think.

**Comment by lucastheisen** [comment]
@bpiwowar, I forgot to mention, let me know when you are done testing this and are ready for a release.  I would be happy to do that as soon as you have all of your bug fixes submitted.

**Comment by bpiwowar** [comment]
Tested with the SftpFileSystem; would it be possible to have a simpler scheme, as e.g. `sftp.unix` as it will always be an "hybrid" filesystem anyways ?

**Comment by bpiwowar** [comment]
btw, ready for a release

**Comment by lucastheisen** [comment]
> would it be possible to have a simpler scheme, as e.g. sftp.unix as it will always be an "hybrid" filesystem anyways ?

My intention is to eventually release a pure `sftp` implementation.  The only limitation I encountered is that the most common version (3) does not support user names, so i would be forced to use uid.  Though I can detect a more current version capable of the feature required for actual names...  Anyway, because I intend to have a pure `sftp` implementation, i think it best to keep the long name here (as ugly as it may be).

> btw, ready for a release

Released as version [0.1.7](http://search.maven.org/#artifactdetails|com.pastdev|jsch-nio|0.1.7|jar)

**Pull request closed without merging**
